# Generated by Django 2.2.6 on 2020-01-21 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_auto_20191211_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='img',
            field=models.ImageField(upload_to='blogger/media/'),
        ),
    ]
